export const ComponentStoreSymbol = Symbol()
export const ComponentArgStoreSymbol = Symbol()
export const ModuleHookStoreSymbol = Symbol()
export const CommandClientSymbol = Symbol()
export const ComponentHookSymbol = Symbol()
export const FilePathSymbol = Symbol()
